name = "ANGRY TITANS Christmas"
author = "SCHLVFMVNGEL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da398656898d1bbd109d37e7fa2861f66c4e63a20ff940ab59ffa23c95569987"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.6"
