name = "ANGRY TITANS Christmas"
author = "SCHLVFMVNGEL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f552a9969ab9ba8353ea95437c37119a1cf36c2f5610ccaf976fef1fe44963ec"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.6"
